version: '3'
services:
  webapp-prd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_PORT=${FLASK_PORT}
    command: gunicorn --bind 0.0.0.0:${FLASK_PORT} -w 4 --preload run:app

    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prd  # Specify the name of your database
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    env_file:
      - ./prod.env
    depends_on:
      -   postgres_db_prd
      -   sqlite-db

  postgres_db_prd:
    image: postgres:13
    container_name: postgres_server_prd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prod  # Specify the name of your database
  sqlite-db:
    image: jitesoft/sqlite:latest
    